FROM python:3.11-slim

WORKDIR /app

COPY app.py .


#cmd şekilnde tnaımlanırsa override edilebrek değiştirlilebilir ama entrypointte değiştirlemez

#CMD ["python","app.py"]

ENTRYPOINT ["python","app.py"]


#----------------------CMD(DEFAULT)-----------------------
#cmd varsayılan çalıştırma komutudur docker run ile override eilebilir

#IMAGE BUILD
#docker build -t cmd-test .

#CONTAINER RUN
#docker run cmd-test

#CONTAINER RUN(CMD override)
#docker run cmd-test python app.py hello world


#--------------------ENTRYPOINT------------------------------

#IAMGE BUILD
#docker -t entrypoint-test .

#CONTAINER RUN
#docker run entrypoint-test hello world

